name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/_spm-test.yml
    with:
      xcode_version: "16.4"
      scheme: "RDSUI"
      sdk: "iphonesimulator"
    secrets: inherit
