name: Release (pre-1.0, tags v0.* or UI)

on:
  push:
    tags:
      - 'v0.*'                  # Publish when pushing v0.x.y tags
  release:
    types: [created, published] # Run when release is created/published from the UI
  workflow_dispatch:            # Allow manual runs
    inputs:
      tag:
        description: 'Tag to release (v0.x.y)'
        required: false
        type: string

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref || github.event.release.tag_name || inputs.tag }}
  cancel-in-progress: true

env:
  # Resolve tag for push/release/dispatch events
  TAG_NAME: ${{ github.ref_type == 'tag' && github.ref_name || github.event.release.tag_name || inputs.tag }}
  SCHEME: RDSUI
  WORKSPACE: ReeceDesignSystem.xcworkspace
  DESTINATION: platform=iOS Simulator,name=iPhone 15
  SDK: iphonesimulator

jobs:
  build-test:
    # Allow when: pushing tag v0.*, release with tag v0.*, or manual dispatch with input v0.*
    if: |
      startsWith(github.ref, 'refs/tags/v0.')
      || (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v0.'))
      || (github.event_name == 'workflow_dispatch' && startsWith(inputs.tag, 'v0.'))
    name: Build & Test (Xcode iOS Simulator)
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      # Use Xcode 16.4 (required for iOS 17 SDK on macos-15 runners)
      - name: Select Xcode 16.4
        run: sudo xcode-select -s "/Applications/Xcode_16.4.app/Contents/Developer"

      - name: Install xcpretty
        run: sudo gem install xcpretty --no-document

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Toolchain versions
        run: |
          swift --version
          xcodebuild -version

      - name: List schemes
        run: xcodebuild -list -workspace "$WORKSPACE"

      - name: Build (iOS Simulator)
        run: |
          set -eo pipefail
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -destination "$DESTINATION" \
            -sdk "$SDK" \
            -configuration Release \
            -skipPackagePluginValidation \
            build | xcpretty

      - name: Test (iOS Simulator)
        run: |
          set -eo pipefail
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -destination "$DESTINATION" \
            -sdk "$SDK" \
            -configuration Release \
            -enableCodeCoverage YES \
            -skipPackagePluginValidation \
            test | xcpretty

  github-release:
    needs: build-test
    if: |
      startsWith(github.ref, 'refs/tags/v0.')
      || (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v0.'))
      || (github.event_name == 'workflow_dispatch' && startsWith(inputs.tag, 'v0.'))
    name: GitHub Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          generate_release_notes: true
          prerelease: true
          fail_on_unmatched_files: false
