name: Release (pre-1.0, tags v0.* or UI)

on:
  push:
    tags:
      - 'v0.*'                  # Publish when pushing v0.x.y tags
  release:
    types: [created, published] # Also run when release is created from the UI
  workflow_dispatch:            # Allow manual runs if needed

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref || github.event.release.tag_name }}
  cancel-in-progress: true

env:
  # Resolve tag for both push and release events
  TAG_NAME: ${{ github.ref_type == 'tag' && github.ref_name || github.event.release.tag_name }}

jobs:
  build-test:
    # Run on tag pushes v0.* or on release events whose tag matches v0.*
    if: startsWith(github.ref, 'refs/tags/v0.') || (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v0.'))
    name: Build & Test (SwiftPM)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Swift version
        run: swift --version

      - name: Build (release)
        run: swift build --configuration release

      - name: Test
        run: swift test --parallel

  release:
    needs: build-test
    # Same condition as build-test to keep logic aligned
    if: startsWith(github.ref, 'refs/tags/v0.') || (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v0.'))
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          generate_release_notes: true
          prerelease: true
          fail_on_unmatched_files: false
