name: Release (pre-1.0, tags v0.*)

on:
  push:
    tags:
      - 'v0.*'   # Solo releases pre-1.0

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    if: startsWith(github.ref, 'refs/tags/v0.')
    name: Build & Test (SwiftPM)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Swift version
        run: swift --version

      - name: Build (release)
        run: swift build --configuration release

      - name: Test
        run: swift test --parallel

  release:
    if: startsWith(github.ref, 'refs/tags/v0.')
    name: GitHub Release
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true  # marcar como pre-release visualmente en GitHub
